config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  resources :messages

  devise_for :users,  :controllers => { registrations: 'users/registrations' }

  devise_scope :user do

    get '/users/matches/:id'  => 'users#matches', as: :user_matches
    post '/users/add_turd' => 'users#add_turd', as: :user_add_turd

    authenticated :user do
      root :to => 'profiles#show', as: :authenticated_root
    end

    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
    post '/profiles/:id(.:format)' => 'profiles#update_photo'
    get '/profiles/show_user/:id(.:format)' => 'profiles#show_user', :as => :profiles_show
    get '/profiles/shitty_answers/:id(.:format)' => 'profiles#shitty_answers', :as => :answers_show
    get '/profiles/user_answers/:id(.:format)' => 'profiles#user_answers', :as => :user_answers_show
    post '/profiles/:id/edit(.:format)' => 'profiles#edit_profile', :as => :edit_profile_profile

  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :profile_photo, ProfilePhotoUploader
  validates :whoami, presence: true
  validates :bio, presence: true

   QUESTIONS = [
[:pizza_beer, "Pizza or Beer?", ["Pizza","Beer","Both"]],
[:drugs, "Drugs or Marijuana?", ["Drugs","Marijuana","Neither"]],
[:concept_reality, "Concept or Reality?", ["Concept","Reality","Both"]],
[:moms_dads, "Moms or Dads?", ["Moms","Dads","Both"]],
[:sandles_socks, "Socks or Sandals?", ["Socks","Sandals","Both"]],
[:europe_paris, "Europe or Paris?", ["Europe","Paris","Both"]],
[:trucks, "Trucks or Four Wheelers?", ["Trucks","Four Wheelers","Both"]],
[:sleater_kelly, "Sleater Kinney or Kelly Slater?", ["Sleater Kinney","Kelly Slater","Both"]],
[:theory_practice, "Theory or Practice?", ["Theory","Practice","Both"]],
[:isp, "Comcast or Time Warner?", ["Comcast","Time Warner","Neither"]],
[:crew, "Crew Neck and Crew Cut or Crew Sock and Crew?", ["Crew Neck and Crew Cut","Crew Sock and J.Crew","Both"]],
[:more_less, "More or Less?", ["More","Less","Both"]],
[:reggae_mouse, "Reggae or Eek A Mouse?", ["Reggae","Eek a Mouse","Both"]],
[:jobs, "Two Jobs or One Job?", ["Two Jobs","One Job","Neither"]],
[:pets_cats, "Pets or Cats?", ["Pets","Cats","Both"]],
[:red_white, "Red or White?", ["Red","White","Rosé"]],
[:sport_ball, "Football and Baseball or Basketball and Hockey?", ["Football and Baseball","Basketball and Hockey","Both"]],
[:meat_murder, "Meat or Murder?", ["Meat","Murder","Both"]],
[:art_commerce, "Art or Commerce?", ["Art","Commerce","Both"]],
[:butler_judith, "Judith Butler or Lee Daniels' 'The Butler'", ["Judith Butler","Lee Daniels' 'The Butler'","Both"]],
[:fleetwood_mcdonalds, "Fleetwood Mac or McDonald's?", ["Fleetwood Mac","McDonalds","Both"]],
[:skate_die, "Skate or Die?", ["Skate","Die","Both"]],
[:sanders, "Bernie or Deion Sanders?", ["Bernie Sanders","Deion Sanders","Both"]],
[:midwest_east, "Midwest or Middle East?", ["Midwest","Middle East","Both"]],
[:modest_eek, "Modest Mouse or Eek A Mouse?", ["Modest Mouse","Eek A Mouse","Both"]],
[:pride_prejudice, "Pride or Prejudice?", ["Pride","Prejudice","Both"]],
[:dwi_dui, "DWI or DUI?", ["DWI","DUI","Both"]],
[:show_tell, "Show or Tell?", ["Show","Tell","Both"]],
[:pat_vanna, "Pat Sajak or Vanna White?", ["Pat Sajak","Vanna White","Both"]],
[:beach, "Aruba, Jamaica or Bermuda, Bahama?", ["Aruba, Jamaica","Bermuda, Bahama","Kokomo"]],
[:peanut_jelly, "Peanut Butter or Jelly", ["Peanutbutter","Jelly","Both"]],
[:animal_boys, "Animal Collective or Beach Boys?", ["Animal Collective","Beach Boys","Both"]],
[:fireman_spaceman, "Fireman or Spaceman?", ["Fireman","Spaceman","Both"]],
[:games_sports, "Games or Sports?", ["Games","Sports","Both"]],
[:seitan_satan, "Seitan or Satan?", ["Seitan","Satan","Both"]],
[:one_fish, "One Fish or Two Fish?", ["One Fish , Two Fish","Three Fish, Blue Fish","Both"]],
[:sixnine_fourtwenty, "69 or 420?", ["69","420","666"]],
[:mint_ice, "Mint Condition or Mint Ice Cream?", ["Mint Condition","Mint Ice Cream","Both"]],
[:marriage_divorce, "Marriage or Divorce?", ["Marriage ","Divorce","Neither"]],
[:steve_jane, "Jane Austen or Steve Austin?", ["Jane Austen","Steve Austen","Both"]],
[:marco_polo, "Marco or Polo?", ["Marco","Polo","Both"]],
[:where_who, "Where am I or Who am I?", ["Where am I","Who am I","Both"]],
[:mfa_mba, "MFA or MBA?", ["MFA","MBA","Both"]],
[:soup_salad, "Soup or Salad?", ["Soup","Salad","Neither"]],
[:paper_plastic, "Paper or Plastic?", ["Paper","Plastic","Both"]],
[:cut_uncut, "Cut or Uncut?", ["Cut","Uncut","Both"]],
[:summer_wrestle, "Summer Slam or Wrestlemania?", ["Summer Slam","Wrestlemania","Neither"]],
[:bush_clinton, "Bush or Clinton?", ["Bush","Clinton","Neither"]],
[:perot_buchanan, "Perot or Buchanan?", ["Perot","Buchanan","Trump"]],
[:pizza_taco, "Pizza Hut or Taco Bell?", ["Pizza Hut","Taco Bell","Both"]],
[:molly_lucy, "Molly or Lucy?", ["Molly","Lucy","Both"]],
[:energy, "Wind or Solar?", ["Wind","Solar","Petroleum"]],
[:pitcher_tallboy, "Pitcher or Tallboy?", ["Pitcher","Tallboy","Both"]],
[:shirts_skins, "Shirts or Skins?", ["Shirts","Skins","Both"]],
[:spark_tap, "Sparkling or Tap?", ["Sparkling","Tap","Both"]],
[:rap_metal, "Rap or Metal?", ["Rap","Metal","Both"]],
[:brush_floss, "Brush or Flossing?", ["Brush","Floss","Neither"]],
[:vinyl_flac, "Vinyl or Flac?", ["Vinyl","FLAC","Neither"]],
[:yes_no, "Yes or No?", ["Yes","No","Both"]],
[:hbo_Sho, "HBO or Showtime?", ["HBO","Showtime","Neither"]],
[:privelage, "Privilege or Responsibility?", ["Privilege ","Responsibility","Both"]],
[:business_pleasure, "Business or Pleasure?", ["Business","Pleasure","Neither"]],
[:liquor_before, "Liquor before Beer or Beer before Liquor?", ["Liquor before Beer","Beer before Liquor","Both"]],
[:sunrise_set, "Sunrise or Sunset?", ["Sunrise","Sunset","Both"]],
[:hall_oates, "Hall or Oates?", ["Hall","Oates","Both"]],
[:simon_garfunkle, "Simon or Garfunkle", ["Simon","Garfunkle","Both"]],
[:beatles, "George or Ringo?", ["George","Ringo","Deez Nuts"]],
[:stick_tribal, "Stick and Poke or Tribal?", ["Stick and Poke","Tribal","Both"]],
[:nor_so, "Norcal or Socal?", ["Norcal","Socal","Neither"]],
[:gluten_mumia, "Gluten Free or Free Mumia?", ["Gluten Free","Free Mumia","Both"]],
[:mac_pc, "Mac or PC?", ["Mac","PC","Neither"]],
[:netflix_chill, "Netflix or Chill?", ["Netflix","Chill","Both"]],
[:fat_jerry, "Fuck Jerry or The Fat Jew?", ["Fuck Jerry","The Fat Jew","Neither"]],
[:friends_benefit, "Friends or Benefits?", ["Friends","Benefits","Both"]],
[:duck_goose, "Duck or Goose?", ["Duck","Goose","Neither"]],
[:black_monday, "Black Friday or Cyber Monday?", ["Black Friday","Cyber Monday ","Both"]],
[:eeny_meeny, "Eeny Meeny or Miny Moe?", ["Eeny Meeny","Miny Moe","Both"]],
[:chicken_egg, "Chicken or Egg?", ["Chicken","Egg","Both"]],
[:calvin_hobbes, "Calvin or Hobbes?", ["Calvin","Hobbes","Both"]],
[:space, "Space or  ?", ["Space"," ","Both"]],
[:beard_moustache, "Beard or Moustache?", ["Beard","Moustache","Both"]],
[:beard_bread, "Beard or Bread?", ["Beard","Bread","Both"]],
[:protoplasm_ectoplasm, "Protoplasm or Ectoplasm?", ["Protoplasm","Ectoplasm","Both"]],
[:liberty_diving, "Libery Bell or Diving Bell?", ["Liberty Bell","Diving Bell","Both"]],
[:preteen_tween, "Preteen or Tween?", ["Preteen","Tween","Both"]],
[:neither_either, "Neither or Either?", ["Neither","Either","Both"]],
[:rock_lock, "Pop Rock or Pop Lock?",["Pop Rock","Pop Lock","Both"]],
[:tang_capri, "Tang or Capri Sun?",["Tang","Capri Sun","Both"]],
[:pool_ball, "Pool Cue or Cue Ball?",["Pool Cue","Cue Ball","Both"]],
[:golf_fishing, "Golf or Fishing?",["Golf","Fishing","Neither"]],
[:duck_goose, "Duck or Goose?",["Duck","Goose","Both"]],
[:red_blue, "Red Pill or Blue Pill?",["Red Pill","Blue Pill","Both"]],
[:love_hate, "I Love You or I Hate You?",["I Love You","I Hate You","Both"]],
[:vim_emacs, "Vim or Emacs?",["Vim","Emacs","Neither"]],
[:york_jersey, "New York or New Jersey?",["New York","New Jersey","Neither"]],
[:desert_tundra, "Desert or Tundra?",["Desert","Tundra","Both"]],
[:green_ice, "Greenland or Iceland?",["Greenland","Iceland","Both"]],
[:ball_meth, "Crystal Ball or Crystal Meth?",["Crystal Ball","Crystal Meth","Both"]],
[:bye_riddance, "Good Bye or Good Riddance?",["Good Bye","Good Riddance","Both"]],
[:aliefs_beliefs, "Aliefs or Beliefs?",["Aliefs","Beliefs","Both"]],
[:gophers_groundhogs, "Gophers or Groundhogs?",["Gophers","Groundhogs","Both"]],
[:felony_misdemeanor, "Felony or Misdemeanor?",["Felony","Misdemeanor","Both"]],
[:peaches_herb, "Peaches or Herb?", ["Peaches","Herb","Neither"]], 
[:juggalo_bungalow, "Juggalo or Bungalow?", ["Juggalo","Bungalow","Both"]], 
[:pecan_duncan, "Pecan Sandies or Sandy Duncan?", ["Pecan Sandies","Sandy Duncan","They're the same thing."]], 
[:gummy_sandals, "Gummy Vitamins or Jelly Sandals", ["Gummy Vitamins","Jelly Sandals","Both"]], 
[:fela_bela, "Fela Kuti or Bela Fleck?", ["Fela Kuti","Bela Fleck","Both"]], 
[:eggo_ego, "Eggo or Ego?", ["Eggo","Ego","Both"]], 
[:seger_dylan, "Early Seger or Late Dylan?", ["Early Seger","Late Dylan","Both"]], 
[:kleenex_skrillex, "Kleenex or Skrillex?", ["IYDKYDG","Skrillex","Neither"]], 
[:smoke_bowls, "Smoking at Bowling or Smoking a Bowl?", ["Smoking at Bowling","Smoking a Bowl","Both"]], 
[:webbed_nipple, "Webbed Toes or Third Nipple?", ["Webbed Toes","Third Nipple","Both"]], 
[:zoobilee_riot, "Zoobilee Zoo or Zoot Suit Riot?", ["Zoobilee Zoo"," Zoot Suit Riot","Neither"]], 
[:have_hold, "To Have or To Hold?", ["To Have","To Hold","Both"]], 
[:mandles, "Mandles or Guyliner?", ["Mandles","Guyliner","Shut up"]], 
[:rat_duck, "Rattails or Duck Tales?", ["Rattails"," Duck Tales","Both"]], 
[:mandatory_overdrive, "Mandatory Minimums or Maximum Overdrive?", ["Mandatory Minimums","Maximum Overdrive","Neither"]], 
[:townhouse_zandt, "Townes Van Zandt or Townhouse Crackers?", ["Townes Van Zandt","Townhouse Crackers","Both"]], 
[:jedi_jew, "Judaism or Jedism?", ["Judaism","Jedism","Both"]], 
[:lydia_lunchables, "Lunchables or Lydia Lunch?", ["Lunchables","Lydia Lunch","Both"]], 
[:appeteaser, "Appeteasers or Anytizers?", ["Appeteasers","Anytizers","Both"]], 
[:opp_dna, "OPP or DNA?", ["OPP","DNA","Both"]], 
[:pauly_cole, "Pauly Shore or Paula Cole?", ["Pauly Shore","Paula Cole","Neither"]], 
[:deuce_man, "Deuce Bigelow or The Ladies' Man?", ["Deuce Bigelow","The Ladies' Man","Both"]], 
[:paul_report, "Paul Blart Mall Cop or Observe & Report?", ["Paul Blart Mall Cop ","Observe & Report","Neither"]], 
[:lmfao_schwarts, "LMFAO or FAO Schwartz?", ["LMFAO","FAO Schwartz","Both"]], 
[:blind_massacre, "Blind Melon or The Brian Jonestown Massacre?", ["The Dandy Warhols","The Brian Jonestown Massacre","Who?"]], 
[:ebola_ricola, "Ebola or Ricola?", ["Ebola","Ricola","Neither"]], 
[:march_martha, "Martha Washington or The March on Washington?", ["Martha Washington","The March on Washington","Both"]], 

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<div class='container'>
    <div class="col-md-3 col-md-offset-0">
<%= simple_form_for @profile do |f| %>

  <%= f.input @questions[0][0], :collection => @questions[0][2], :label => @questions[0][1] %>
  <%= f.button :submit, "Answer Question" %>

<% end %>
</div>
</div>

app/views/profiles/edit_profile.html.erb
<div class = 'container'>
<% if user_signed_in? %>
<%= current_user.user_name %> 
<%= simple_form_for @profile do |f| %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :zip_code %>
  <%= f.input :bio, label: 'Describe yourself in 69 characters', :input_html => {:maxlength => 69, :size => 50}, required: true%>
  <%= f.input :whoami, :collection => ['a shitty dude','seeking a shitty dude','both'], required: true, :label => 'I am...' %>

  <%= f.submit "Update and Answer More Questions"%>
<% end %>
<% end %>

</div>

app/views/profiles/new.html.erb
<div class = 'container'>
<% if user_signed_in? %>
<%= current_user.user_name %>	
<%= simple_form_for @profile do |f| %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :zip_code %>
  <%= f.input :bio, label: 'Describe yourself in 69 characters', :input_html => {:maxlength => 69, :size => 50}, required: true%>
  <%= f.input :whoami, :collection => ['a shitty dude','seeking a shitty dude','both'], required: true, :label => 'I am...' %>
  <%= f.input :sandles_socks, :collection => ['Sandles','Socks','Both'], :label => 'Sandles or Socks' %>
  <%= f.file_field :profile_photo %>
  <%= f.hidden_field :profile_photo_cache %>
  <%= f.input :account_id, :as => :hidden, :input_html => { :value => current_user.id } %>
  <%= f.button :submit %>
<% end %>

  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
</div>

app/views/profiles/shitty_answers.html.haml
- @questions.each do |q|
	= simple_form_for @profile,  :html => { item_wrapper_class: 'inline' } do |f|
		= f.input q[0], label: q[1], as: :check_boxes, collection: q[2]

app/views/profiles/show.html.haml
.container
	.row
		.col-md-4
			<p class='user_name'>My Profile</p>
			- if @profile.profile_photo.present?
				= image_tag "#{@profile.profile_photo}", :class => "profile_image", size: "300x300"
				<p class='upload_image'>Change profile photo</p>
				= simple_form_for @profile,:method => 'update_photo', :html =>  { :multipart => true } do |f| 
					= f.file_field :profile_photo
					= f.hidden_field :profile_photo_cache 
					= f.input :account_id, :as => :hidden, :input_html => { :value => current_user.id }
					= f.button :submit, "Update Photo", :class => 'btn btn-small'
			- else
				= image_tag("default_profile_photo.png")
				= simple_form_for @profile,:method => 'update_photo' do |f| 
					= f.file_field :profile_photo
					= f.hidden_field :profile_photo_cache 
					= f.input :account_id, :as => :hidden, :input_html => { :value => current_user.id }
					= f.button :submit, "Add Photo", :class => 'btn btn-small'


		.col-md-8
			<br>
			<br>
			<br>
			<br>
			<p class='bio'>Me in 69 characters or less</p>
			= "#{@profile.bio}"
			<br>
			<br> 
			.whoami
				I am ... #{@profile.whoami}
			<br>
			<br>
			<br>
			= image_tag('Smiling_poo_emoji.jpg', size: '50x50')
			I have been turded #{@profile.user.turds} times! Congratulations!
			<br>
			<br>
			= button_to "Cancel My Account", user_registration_path, :confirm => "Are you sure?", :method => :delete, :class => 'btn btn-small btn-danger' 
			<br>
			= link_to "Edit My Profile", edit_profile_profile_path(@user.id), :method => :edit, :class => 'btn btn-small btn-warning'

app/views/profiles/show_user.html.haml
.col-md-6.col-sm-1.col-md-offset-3
  .intro-text
    - if #{@user.user_name}.downcase == 'both'
      %h3 This is #{@user.user_name}, who is both a shitty dude and is seeking other shitty dudes.
    - else 
      %h3 This is #{@user.user_name}, who is #{@profile.whoami}.

  %br
  .message-link
    = link_to '', new_message_path({receiver_id: @user.id}), class: "glyphicon glyphicon-envelope"
  %br
  .turd-button
    = link_to image_tag('Smiling_poo_emoji.jpg', size: '50x50'), user_add_turd_path({id: @profile.id}), method: :post
    = @user.turds

  %br
  .answers-show-link
    = link_to "#{@user.user_name}'s Shitty Answers", user_answers_show_path({id: @user.profile.id})

  %br
  .profile_image
    - if @profile.profile_photo.present?
      = image_tag "#{@profile.profile_photo}", size: "300x300"
    - else
      = image_tag("default_profile_photo.png")
  %br
  .profile_bio
  - if defined? @profile.bio
    <center>
    <b>In 69 characters or less:</b>
    = "#{@profile.bio}"
    </center>

app/views/profiles/user_answers.html.haml
.container
  .user_answers.col-md-6.col-md-offset-3.col-sm-12
    - @questions.each do |q|
      = simple_form_for @profile,  :html => {:class => 'input-group col-sm-12 col-lg-12 form-horizontal'} do |f|
        = f.input q[0], label: q[1], as: :check_boxes, collection: q[2], :disabled => true
      %hr