config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  resources :messages

  devise_for :users,  :controllers => { registrations: 'users/registrations' }

  devise_scope :user do

    get '/users/matches/:id'  => 'users#matches', as: :user_matches
    post '/users/add_turd' => 'users#add_turd', as: :user_add_turd

    authenticated :user do
      root :to => 'profiles#show', as: :authenticated_root
    end

    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
    post '/profiles/:id(.:format)' => 'profiles#update_photo'
    get '/profiles/show_user/:id(.:format)' => 'profiles#show_user', :as => :profiles_show
    get '/profiles/shitty_answers/:id(.:format)' => 'profiles#shitty_answers', :as => :answers_show
    get '/profiles/user_answers/:id(.:format)' => 'profiles#user_answers', :as => :user_answers_show
    post '/profiles/:id/edit(.:format)' => 'profiles#edit_profile', :as => :edit_profile_profile

  end

end

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67225794-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.haml
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Shitty Dude Finder: Find Shitty Dudes or People Who Like Shitty Dudes</title>
= javascript_include_tag 'application' 
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css' 
= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/4.9.0/bootstrap-social.min.css' 

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all' 
<meta name="description" content="Plenty of Turds in the Sea. Shitty Dude Finder helps connect shitty dudes to those who seek shitty dudes.">  
<link rel="canonical" href="http://shittydudefinder.com/">
</head>
<body>
.navbar.navbar-default{:role => 'navigation'}
  .container-fluid
    .navbar-header
      - if current_user
        .navbar-brand= link_to 'ShittyDudeFinder', authenticated_root_path
      - else
        .navbar-brand= link_to 'ShittyDudeFinder', unauthenticated_root_path


      %button.navbar-toggle{'type' => 'button', 'data-toggle' => "collapse",  'data-target' => "#navbartarget"}
        %span.glyphicon.glyphicon-align-justify
        %span.sr-only Toggle Only
    .collapse.navbar-collapse#navbartarget{:role => 'navigation'}
      %ul.nav.navbar-nav
        - if current_user
          %li.hellomessage Hello, #{current_user.user_name.humanize}
          - if current_user.profile.id
            %li
              = link_to 'Answer Shitty Questions', edit_profile_path(current_user)
          %li
            = link_to 'Browse Shitty Dudes', user_matches_path(current_user)
          %li
            = link_to 'Inbox', messages_path(:mailbox=>:inbox)
          %li
            = link_to 'My Profile', authenticated_root_path
          %li
            = link_to 'Sign Out', destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'Sign Up', new_user_registration_path
          %li
            = link_to 'Login', new_user_session_path
    -flash.each do |key, value|
      %div{class: "alert alert-#{key}"} 
        = value
</body>
= yield
= render 'layouts/footer' 
</html>